### PR TITLE
Add support for Trade Window

### PR DESCRIPTION
**Pull request by caxerx**
Add offset for player trade window and element support

### CODE REVIEW

**Comment by lampii** [comment]
Works great! @caxerx Can you explain how you determined your GameOffsets? I want to take a stab at adding the party Elements but I havent been able to figure out the correlation between the nested Element and the top level InGameUiElement Address

**Comment by caxerx** [comment]
> Works great! @caxerx Can you explain how you determined your GameOffsets? I want to take a stab at adding the party Elements but I havent been able to figure out the correlation between the nested Element and the top level InGameUiElement Address

I look it on the dev tree. When you hover to an UI element and the selected UI element will be highlighted.
For the social tab, you can see the offset is 540. The UI element has 3 children and the main content of current party is in the last children.

**Comment by lampii** [comment]
Got it thanks! I spent a bit of time this weekend and realized the base address + offsets are just pointers to their respective memory sections containing the parent element for that group. I managed to add most of the social tab which has been working great. I will throw a PR to add it once I prune down the un-necessary elements.  My focus has now shifted to fixing 'NearestPlayers' as the expected memlocs are wrong half the time due to there being empty elements in the middle of the list.

**Comment by stevefan1999-personal** [comment]
> 
> 
> Got it thanks! I spent a bit of time this weekend and realized the base address + offsets are just pointers to their respective memory sections containing the parent element for that group. I managed to add most of the social tab which has been working great. I will throw a PR to add it once I prune down the un-necessary elements. My focus has now shifted to fixing 'NearestPlayers' as the expected memlocs are wrong half the time due to there being empty elements in the middle of the list.

@lampii Change all the types to IntPtr bruh

**Pull request closed without merging**
