### PR TITLE
Update packages, add missing ImGUI lib

### PR DESCRIPTION
**Pull request by dukenuking**
might be useful.
Updated all packages and added the missing ImGUI nuget package

### CODE REVIEW

**Comment by zaafar** [comment]
Have you tested it? Does it work after all the packages changes and everything?

**Comment by dukenuking** [comment]
Yeah, currently playing with it, I had to copy other files as offsets and sounds/fonts etc from the release to make it work, there is one error that needs fixing(https://github.com/dukenuking/ExileApi/commit/e7e50b63b7e7327db2aac3c4b17e102f7d576e0a) but i wanted to push this one first, if this one gets merged I can make new pull req

**Comment by zaafar** [comment]
Did you manually copy the new dlls from the updated packages folder to the release folder?

**Comment by dukenuking** [comment]
This is only stuff  I had to copy paste from release.
Files:
- GameOffsets.dll

Folders & contents of it:

- Config folder
- Fonts
- Logs (had to create, else u get file not found error at run-time)
- Plugins(not all of them just flask manager)
- Shaders
- Sounds
- Textures

**Comment by zaafar** [comment]
Just tested it locally and its working fine.
However it breaks the pickit plugin as shown below (which I can fix later on).

feel free to create a PR for (dukenuking@e7e50b6) 


```
2019-09-08 16:53:05.089 -04:00 [Error] Plugin Pickit error init System.IO.FileLoadException: Could not load file or assembly 'MoreLinq, Version=3.1.1.0, Culture=neutral, PublicKeyToken=384d532d7e88985d' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'MoreLinq, Version=3.1.1.0, Culture=neutral, PublicKeyToken=384d532d7e88985d'
   at PickIt.PickIt.LoadPickit(String fileName)
   at PickIt.PickIt.LoadRuleFiles() in A:\Work\BitBucket\ExileApi\PickIt\PickIt.cs:line 528
   at PickIt.PickIt.Initialise() in A:\Work\BitBucket\ExileApi\PickIt\PickIt.cs:line 62
   at Shared.PluginManager.InitPlugin(IPlugin plugin) in C:\Users\Zaafar\Desktop\development-work\ExileApi\Core\Shared\PluginManager.cs:line 352

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

**Comment by dukenuking** [comment]
Oh ok, guess ill have to copy paste all plugins to test it "fully"

**Comment by zaafar** [comment]
yeah, if a plugin and the core HUD uses the same lib there would be a problem whenever we update the core libs.

**Pull request merged**
